fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.15.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: 'v1.3.0'
  symlinks:
    oauth2_proxy: "#{source_dir}"
